"""Message bobody

Revision ID: b4da210dce62
Revises: 5610023a8206
Create Date: 2018-12-07 21:36:42.943718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4da210dce62'
down_revision = '5610023a8206'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('body', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'body')
    # ### end Alembic commands ###
